permissions: read-all
concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}
jobs:
  portfolio-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix run .#portfolio-lint

  eslint-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e
      - uses: actions/setup-node@aca7b64a59c0063db8564e0ffdadd3887f1cbae5
        with:
          node-version: 22
      - run: npm ci
      - run: npm run check
      - run: npm run eslint
      - run: npm run format:check
      - run: npm run cy:eslint

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e
      - uses: cypress-io/github-action@40cfd368ca72ba2bcbe95f70ddcc66136ca3183d
        with:
          build: npm run build
          start: npm start

name: dev
on:
  pull_request:
    branches: [main]
